### ISSUE TITLE
ClientRequestError: Bad Request (Status Code 400) for Unsupported Insert Operation

### ISSUE THREAD

**Issue by rtweera** [rtweera/ollama.text#2]
When attempting to perform an `insert` operation (i.e., `suffix`) using the Ballerina connector for Ollama, the client encounters a `ClientRequestError` with a status code of 400. The error indicates that the `registry.ollama.ai/library/deepseek-r1:latest` does not support insert operations. Further, the same with `llama3.2` and `mistral`.

### Steps to Reproduce:

Use the Ballerina connector for Ollama to perform an insert operation.
Ensure the operation targets the registry.ollama.ai/library/deepseek-r1:latest.

**Expected Behavior:** The insert operation should be successfully executed without errors.

**Actual Behavior:** The client returns a ClientRequestError with the following details:
```yaml
Status Code: 400
Headers:
  Content-Length: 81
  Content-Type: application/json; charset=utf-8
  Date: Wed, 19 Mar 2025 09:29:03 GMT
Body: {"error":"registry.ollama.ai/library/deepseek-r1:latest does not support insert"}
```
**Proposed Solution:** Investigate the compatibility of the registry.ollama.ai/library/deepseek-r1:latest with insert operations and update the client code or documentation to reflect supported operations.

### Additional Information:

Ballerina version: Ballerina 2201.12.0
Ollama API version: 0.6.0
